arch:
  - amd64
  - ppc64le
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libelf-dev gcc-avr avr-libc freeglut3-dev

language: c
script:
- make V=1
- make -C tests run_tests V=1
