#!/bin/sh

TESTS=`find . -maxdepth 1 -executable -name test_\*`

num_failed=0
num_run=0

for test in $TESTS; do
    num_run=$(($num_run+1))
    if ! $test; then
	echo "$test returned with exit value $?."
	num_failed=$(($num_failed+1))
    fi
done

echo "Tests run: $num_run  Successes: $(($num_run-$num_failed))  Failures: $num_failed"
